### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by kutawhat** [maxcurzi/tplay#29]
Is it possible that you will make a MacOS version?

**Comment by maxcurzi** [comment]
Hi,

I don't have a Mac, nor experience with developing software on it, unfortunately  It would be cool if someone gave it a go and lets me know 

It's tricky enough as it is to get OpenCV to work well on different Linux distributions :)

Maybe one day I'll use simpler dependencies...

Cheers,
Max

**Comment by kutawhat** [comment]
Got it, thanks for answering!
