### ISSUE TITLE
[INFO] `tplay` is available as a nix package

### ISSUE THREAD

**Issue by C0Florent** [maxcurzi/tplay#41]
This is just a heads-up for any maintainer to update the project README, since the current information "The package is not currently available on [non-arch] Linux distros" is not true.

`tplay` being a nix package means it can be installed separately from the rust toolchain on any machine where the `nix` package manager is installed (potentially any linux distro), and also makes it available as a system package on NixOS.

---

By the way, tplay is the [third result when searching "media player" in nix packages](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=media+player), this is how I got to know about this project, about 1 hour ago.
I also noticed some dependency issues when trying to use it (needed to manually specify additional dependencies to make the package work), which I've opened [an issue for over the nix pacakages repo](https://github.com/NixOS/nixpkgs/issues/326223). I just leave this as a side note if you're willing to try running it, just for it to make some more sense if it doesn't work.

**Comment by maxcurzi** [comment]
Thanks! I'll have a look and update it
