### ISSUE TITLE
Add donation methods

### ISSUE THREAD

**Issue by hardBSDk** [maxcurzi/tplay#43]
This program is amazing and must be maintained/supported, thus I suggest for you to add donation methods.

I recommend the following methods:

- Bitcoin
- Monero
- Patreon
- GitHub Sponsors

**Comment by maxcurzi** [comment]
thanks for the suggestion :) I don't have much time to support this project to its full potential so I'd feel bad about accepting donations!
I'll look into it nevertheless, I didn't know about GitHub Sponsors
