### ISSUE TITLE
[BUG] CANNOT INSTALL ON ARCH LINUX

### ISSUE THREAD

**Issue by lunar-Crawler** [maxcurzi/tplay#49]
**Describe the bug**
CANNOT INSTALL THE AUR PACKAGE ( TPLAY-GIT )

**To Reproduce**
USING PARU OR MAKEPKG PRODUCES THE SAME ERROR

**Expected behavior**
BEING ABLE TO INSTALL THE PACKAGE

**Screenshots**
LOGS  FROM "paru -S tplay-git" https://hastebin.com/share/yonidagada.yaml

**Desktop**
 - OS: ARCH LINUX, 
- `tplay  --version`: N/A
- `yt-dlp --version`: 2024.10.22
- `mpv --version`: 0.39.0
- `rustc --version`: 1.82.0
- `pkg-config --modversion opencv4`: <4.10.0
- `ffmpeg -version`: n7.0.2

**Additional context**
SAME ISSUE AS https://aur.archlinux.org/packages/tplay-git#comment-951678

**Comment by maxcurzi** [comment]
FFMPEG 7 is not currently supported. 
For now only FFmpeg versions: 3.4.x through 4.4.x will work.
I'll update the various dependencies as soon as I can, but it won't be as straightforward as changing a number in cargo.toml so it may take me some time.

**Comment by neon-mmd** [comment]
> **Describe the bug** CANNOT INSTALL THE AUR PACKAGE ( TPLAY-GIT )
> 
> **To Reproduce** USING PARU OR MAKEPKG PRODUCES THE SAME ERROR
> 
> **Expected behavior** BEING ABLE TO INSTALL THE PACKAGE
> 
> **Screenshots** LOGS FROM "paru -S tplay-git" https://hastebin.com/share/yonidagada.yaml
> 
> **Desktop**
> 
> * OS: ARCH LINUX,
> * `tplay  --version`: N/A
> * `yt-dlp --version`: 2024.10.22
> * `mpv --version`: 0.39.0
> * `rustc --version`: 1.82.0
> * `pkg-config --modversion opencv4`: <4.10.0
> * `ffmpeg -version`: n7.0.2
> 
> **Additional context** SAME ISSUE AS https://aur.archlinux.org/packages/tplay-git#comment-951678

I think I can provide a temporary fix for this maybe. Right now I am not on my main system. Once I am, I will check this out and rollout a fix as soon as possible. So I would suggest for now you can try installing it manually by following the `readme` instructions. :slightly_smiling_face: .

**Comment by neon-mmd** [comment]
@maxcurzi @lunar-Crawler 
(Sorry for the pings)

I wanted to inform that I have provided a temporary fix for this issue for now. So you should now be able to install `tplay` as usual using the `aur`. But if you face any issues the I would suggest still feel free to reopen this issue and update us on the issue. 🙂

**Comment by maxcurzi** [comment]
Ah so you updated the package's Cargo.toml in AUR only, I didn't know you could do that!
